language: php
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2

before_install:
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose validate

script:
  # Run automated tests.
  - composer install && ./vendor/bin/phpunit
  - cd .. && composer create-project --repository=https://repo-magento-mirror.fooman.co.nz/ magento/project-community-edition:^2.3 m2-folder --no-install --no-interaction
  - cd m2-folder
  - composer config --unset repo.0
  - composer config repo.foomanmirror composer https://repo-magento-mirror.fooman.co.nz/
  - composer install --prefer-dist
  # Check the performance.
  - composer update nothing --profile
  - composer config repositories.local path "../composer-magento2-optimizations" && composer require fooman/composer-magento2-optimizations:@dev
  - composer update nothing --profile
